"""Apple 快捷指令动作标识符 → 中文名映射表。"""

ACTION_CN = {
    "is.workflow.actions.gettext": "获取文本",
    "is.workflow.actions.text": "文本",
    "is.workflow.actions.url": "URL",
    "is.workflow.actions.openurl": "打开 URL",
    "is.workflow.actions.downloadurl": "获取 URL 内容(GET)",
    "is.workflow.actions.getcontentofurl": "获取 URL 内容(POST/自定义)",
    "is.workflow.actions.setclipboard": "拷贝到剪贴板",
    "is.workflow.actions.getclipboard": "获取剪贴板",
    "is.workflow.actions.notification": "显示通知",
    "is.workflow.actions.showresult": "显示结果",
    "is.workflow.actions.alert": "显示提醒",
    "is.workflow.actions.runworkflow": "运行快捷指令",
    "is.workflow.actions.conditional": "如果(条件分支)",
    "is.workflow.actions.menu": "从菜单中选择",
    "is.workflow.actions.choosefrommenu": "从菜单中选择",
    "is.workflow.actions.number": "数字",
    "is.workflow.actions.calculate": "计算",
    "is.workflow.actions.round": "将数字取整",
    "is.workflow.actions.dictionary": "字典",
    "is.workflow.actions.getvalueforkey": "获取词典值",
    "is.workflow.actions.setvalueforkey": "设置词典值",
    "is.workflow.actions.list": "列表",
    "is.workflow.actions.text.match": "匹配文本(正则)",
    "is.workflow.actions.text.replace": "替换文本",
    "is.workflow.actions.text.split": "拆分文本",
    "is.workflow.actions.text.combine": "合并文本",
    "is.workflow.actions.comment": "注释",
    "is.workflow.actions.input": "获取快捷指令输入",
    "is.workflow.actions.output": "输出",
    "is.workflow.actions.exit": "停止快捷指令",
    "is.workflow.actions.wait": "等待",
    "is.workflow.actions.waittoreturn": "等待返回",
    "is.workflow.actions.base64": "Base64 编码",
    "is.workflow.actions.hash": "生成哈希",
    "is.workflow.actions.urlencode": "URL 编码",
    "is.workflow.actions.format.date": "格式化日期",
    "is.workflow.actions.date": "日期",
    "is.workflow.actions.adjustdate": "调整日期",
    "is.workflow.actions.gettimebetween": "获取两个日期之间的时间",
    "is.workflow.actions.detect.language": "检测语言",
    "is.workflow.actions.translate": "翻译",
    "is.workflow.actions.detect.dictionary": "从输入获取词典(解析JSON)",
    "is.workflow.actions.getvariable": "获取变量",
    "is.workflow.actions.setvariable": "设置变量",
    "is.workflow.actions.appendvariable": "添加到变量",
    "is.workflow.actions.ask": "要求输入",
    "is.workflow.actions.choosefromlist": "从列表中选择",
    "is.workflow.actions.filter.files": "筛选文件",
    "is.workflow.actions.getfile": "获取文件",
    "is.workflow.actions.savefile": "存储文件",
    "is.workflow.actions.deletefile": "删除文件",
    "is.workflow.actions.getitemfromlist": "从列表获取项目",
    "is.workflow.actions.getdetailsofitems": "获取项目的详细信息",
    "is.workflow.actions.count": "统计项目数",
    "is.workflow.actions.text.changecase": "更改大小写",
    "is.workflow.actions.round.rate": "评价(评分)",
    "is.workflow.actions.usemodel": "使用模型(Apple Intelligence)",
}
